name: CI/CD for Qt App (Windows - MinGW)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: windows-latest

    env:
      EXE_NAME: TICTAKTOE.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.0'
          target: 'desktop'
          arch: 'win64_mingw'
          setup-python: false

      - name: Build the Qt app
        run: |
          qmake TICTAKTOE.pro -spec win32-g++
          mingw32-make

      - name: Prepare artifact for release
        run: |
          mkdir dist
          copy .\${{ env.EXE_NAME }} dist\

      - name: Upload to GitHub Release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          name: "Release ${{ github.sha }}"
          tag_name: "release-${{ github.run_number }}"
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
