name: CI/CD for Qt App (Windows - MinGW)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: windows-latest

    env:
      EXE_NAME: TICTAKTOE.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.0'
          target: 'desktop'
          arch: 'win64_mingw'
          setup-python: false

      - name: Build the Qt app
        run: |
          qmake TICTAKTOE.pro -spec win32-g++
          mingw32-make

      - name: Debug: List build outputs
        run: |
          dir /s /b *.exe
          dir /s /b *.dll

      - name: Prepare dist folder
        shell: pwsh
        run: |-
          mkdir dist
          $exe = Get-ChildItem -Recurse -Filter $env:EXE_NAME | Select-Object -First 1
          if (-not $exe) {
              Write-Error "Executable $($env:EXE_NAME) not found after build"
              exit 1
          }
          Copy-Item $exe.FullName -Destination dist\

          $dlls = @(
              "Qt6Core.dll",
              "Qt6Gui.dll",
              "Qt6Widgets.dll",
              "libgcc_s_seh-1.dll",
              "libwinpthread-1.dll",
              "libstdc++-6.dll"
          )

          foreach ($dll in $dlls) {
              $dllPath = Get-ChildItem -Recurse -Filter $dll | Select-Object -First 1
              if ($dllPath) {
                  Copy-Item $dllPath.FullName -Destination dist\
              } else {
                  Write-Warning "Warning: DLL $dll not found"
              }
          }

          mkdir dist\platforms
          $platformDll = Get-ChildItem -Recurse -Filter qwindows.dll | Select-Object -First 1
          if ($platformDll) {
              Copy-Item $platformDll.FullName -Destination dist\platforms\
          } else {
              Write-Warning "Warning: qwindows.dll not found"
          }

      - name: Create ZIP of dist folder
        run: Compress-Archive -Path dist\* -DestinationPath TICTAKTOE-win.zip

      - name: Upload ZIP to GitHub Release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          name: "Release ${{ github.sha }}"
          tag_name: "release-${{ github.run_number }}"
          files: TICTAKTOE-win.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
